### ISSUE TITLE
npm install -g alfred-emoji fails

### ISSUE THREAD

**Issue by jordyvandomselaar** [jukben/alfred-emoji#18]
Stacktrace:

```
❯ npm install -g alfred-emoji

> core-js@2.6.9 postinstall /Users/jordyvandomselaar/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-emoji/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> alfred-emoji@0.2.2 postinstall /Users/jordyvandomselaar/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-emoji
> alfy-init

Error: Command failed: alfred-link
Error: `Alfred.alfredpreferences` package does not exist
    at /Users/jordyvandomselaar/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-emoji/node_modules/alfred-link/index.js:27:12


    at makeError (/Users/jordyvandomselaar/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-emoji/node_modules/execa/index.js:174:9)
    at /Users/jordyvandomselaar/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-emoji/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  code: 1,
  stdout: '',
  stderr: 'Error: `Alfred.alfredpreferences` package does not exist\n    ' +
    'at ' +
    '/Users/jordyvandomselaar/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-emoji/node_modules/alfred-link/index.js:27:12\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false,
  killed: false
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-emoji@0.2.2 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alfred-emoji@0.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jordyvandomselaar/.npm/_logs/2019-07-31T12_01_59_284Z-debug.log
```

**Comment by jukben** [comment]
I can't reproduce it. :(

  ```                                                                                                   
pb-frontend feat/analyticsv2-implementation^ ✓ npm install -g alfred-emoji

> core-js@2.6.9 postinstall /usr/local/lib/node_modules/alfred-emoji/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> alfred-emoji@0.2.2 postinstall /usr/local/lib/node_modules/alfred-emoji
> alfy-init

+ alfred-emoji@0.2.2
added 211 packages from 76 contributors in 15.04s

```

Does this path exists for you? `/Users/xxx/Library/Application Support/Alfred/Alfred.alfredpreferences/`. That might be the issue

**Comment by jordyvandomselaar** [comment]
That path does not exist for me because I have it stored somewhere else.
