### ISSUE TITLE
Object.entries is not a function

### ISSUE THREAD

**Issue by codycodes** [jukben/alfred-emoji#2]
```
TypeError: Object.entries is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-emoji/node_modules/@jukben/emoji-search/lib/index.js:20:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-emoji/index.js:5:16)
```

-
Emoji 0.0.3
Alfred 3.5.1
darwin x64 17.2.0

Any way to resolve this with npm?

**Comment by jukben** [comment]
Oh! I will be probably because `node` version. Could you please check your Node version? Try to upgrade to `7.5.0` but I should probably include a shim for it.

**Comment by jukben** [comment]
I've also released `0.0.4` version which should fix your problem instantly.

**Comment by codycodes** [comment]
Thanks for your quick response! So I've tried a few times/ways to install, but they all gave me this error:

```
npm ERR! path /usr/local/lib/node_modules/alfred-emoji/node_modules/match-sorter/node_modules/diacritic
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/alfred-emoji/node_modules/match-sorter/node_modules/diacritic' -> '/usr/local/lib/node_modules/alfred-emoji/node_modules/match-sorter/node_modules/.diacritic.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by codycodes** [comment]
Thanks for your quick response! So I've tried a few times/ways to install, but they all gave me this error:
